<a href="https://colab.research.google.com/github/ikramooe/DataScience-1/blob/master/Digit_Recognizer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np 
import tensorflow as tf 
import matplotlib.pyplot as plt 
from sklearn.model_selection import train_test_split


from google.colab import drive 
drive.mount('/content/gdrive')

import pandas as pd 
train=pd.read_csv('gdrive/My Drive/Colab Notebooks/traindigit.csv')
test=pd.read_csv('gdrive/My Drive/Colab Notebooks/testdigit.csv')

X = train.drop(['label'],axis=1)
Y = train['label']

print(X.shape)
X  = X.values.reshape(-1,28,28,1)
print(X[1])
print(X.shape)
X = X / 255.0

train_images , test_images , train_labels , test_labels = train_test_split(X,Y,test_size=0.2,random_state=0)





#test = test.values.reshape(-1,28,28,1)
test= test / 255.0



model = tf.keras.models.Sequential([
	tf.keras.layers.Conv2D(64,(3,3) , activation='relu' , input_shape=(28,28,1)),
	tf.keras.layers.MaxPooling2D(2,2),
	tf.keras.layers.Conv2D(64,(3,3),activation='relu'),
	tf.keras.layers.MaxPooling2D(2,2),
	tf.keras.layers.Flatten(),
	tf.keras.layers.Dense(128,activation='relu'),
	tf.keras.layers.Dense(10,activation='softmax')
	])
print(model.summary())
model.compile(optimizer='Adam',loss='sparse_categorical_crossentropy',metrics=['accuracy'])
model.fit(train_images,train_labels,epochs=20)
loss = model.evaluate(test_images,test_labels)
print(loss)



results = model.predict(test)

print(results)

# select the indix with the maximum probability
results = np.argmax(results,axis = 1)

results = pd.Series(results,name="Label")
submission = pd.concat([pd.Series(range(1,28001),name = "ImageId"),results],axis = 1)

submission.to_csv("mnist.csv",index=False)

files.download('mnist.csv') 


# 36928 is obtained by 
# 3 *3 *64  psq in the second layer we have the depth of the image is 64  donc 577 
#577 * 64 since we have 64 filters donc 36928params 
 

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).
(42000, 784)
[[[  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]]

 [[  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]]

 [[  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]]

 [[  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  

KeyboardInterrupt: ignored